[build]
  base = "Frontend"
  command = "npm run build" # or npm run build:prod depending on your package.json script
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200