INSERT INTO roles (role_name)
SELECT 'ROLE_ADMIN'
WHERE NOT EXISTS (SELECT 1 FROM roles WHERE role_name = 'ROLE_ADMIN');

INSERT INTO roles (role_name)
SELECT 'ROLE_MENTOR'
WHERE NOT EXISTS (SELECT 1 FROM roles WHERE role_name = 'ROLE_MENTOR');

INSERT INTO roles (role_name)
SELECT 'ROLE_MENTEE'
WHERE NOT EXISTS (SELECT 1 FROM roles WHERE role_name = 'ROLE_MENTEE');
