spring:

  datasource:
    url: ${postgresql://example_postgresql_abber_user:emnCzEfy6lHKGA5IJUbETcnypidTXdhV@dpg-d9o0frjm8hqs73f7ri70-a/example_postgresql_abber}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:

    open-in-view: false

    hibernate:
      ddl-auto: validate

  flyway:

    enabled: true

server:

  port: ${PORT:8081}