spring:
  application:
    name: abber-backend

  profiles:
    active: dev

  datasource:
    url: ${postgresql://example_postgresql_abber_user:emnCzEfy6lHKGA5IJUbETcnypidTXdhV@dpg-d9o0frjm8hqs73f7ri70-a/example_postgresql_abber}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    out-of-order: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false

server:
  port: 8081

logging:
  config: classpath:logback-spring.xml

app:
  frontend-url: http://localhost:5173

  admin:
    email: ${ADMIN_EMAIL:admin@abber.local}
    password: ${ADMIN_PASSWORD:}

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET:kUsRlDeoqwLyXnE6+RBjp6k5WRpOjsGVzJpHrO1fcNFG7ka6YfNXeeSiSD6dPBV9DtwsvF+nUbkyeE509FIqTw==}
      access-token-expiration: 900000
      refresh-token-expiration: 604800000
